[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    skipSetCommits = true

[[redirects]]
  from = "https://fitspace.cy/*"
  to = "https://www.fitspace.cy/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"